### ISSUE TITLE
HS70 Pro Wireless

### ISSUE THREAD

**Issue by Mouse703** [MrSlimbrowser/ReadBatteryLevel#8]
Does this work with the HS70 Pro Wireless? 
I get a 0 in my result file.

**Comment by MrSlimbrowser** [comment]
It probably works but you would have to invest some time. You definitely can't just use the default pointer address offsets I put in the program, those only work for a specific configuration (headset type, iCUE version, probably amount and type of connected devices too).

You would have to find a pointer address manually using [cheat engine](https://www.cheatengine.org/) that points to the battery level value in iCUEs memory. A bit tough if you've never done it before but try to find tutorials for that online ([this one for example](https://www.unknowncheats.me/forum/programming-for-beginners/110375-cheat-engine-finding-base-address-pointer-scan.html)). Then put the address in the configuration file as described [here](https://github.com/MrSlimbrowser/ReadBatteryLevel#finding-offsets).

**Comment by Mouse703** [comment]
Do I enter 85 when my headset is at 85 percent and then run a scan? When I do that i get around 3800 results, I do have quite a lot of corsair hardware.

**Comment by Mouse703** [comment]
Now I'm left with 3 adresses, but when I click change adress, this happens and I cannot see the offsets/baseadress.
![image](https://user-images.githubusercontent.com/76005221/108074480-8890cc80-7069-11eb-90c1-266f4cd16c59.png)

**Comment by Mouse703** [comment]
![image](https://user-images.githubusercontent.com/76005221/108075894-2d5fd980-706b-11eb-9673-bd28ad631568.png)
Forgot to upload my pointer scan^^

**Comment by MrSlimbrowser** [comment]
You can't just hit the "pointer" checkmark on the address you found, that doesn't change that it's not a pointer ^^.
The pointer scan is looking good, that's the right way. Now you have to try to reduce the list by rescanning. I tried it again too, here are some more tips:
- When you hit "Scan for Pointer" in the "Pointer Scanner" menu reduce the  "Max Level" to 5 or even 4. Thats the maximum amount of offsets the pointer has.
- When your list is small enough to look trough it manually, like a couple hundred/thousand pointers, sort them by "Base Address" and ignore all of them that don't start with "THREADSTACK0"-
- If your list is too big, hit "Rescan Pointer" in the "Pointer Scanner" menu, make shure the "Address to find" is the same you scanned for initially (0D01105C for example in your screenshots) and hit okay. That removes all pointers of the list that don't point to that address anymore. Do that as often as necessary. The goal is to reduce the list only a few pointers (the Pointer paths:510337 in your screenshot should be as small as possible). Before hitting rescan click around in iCUE for a bit to change a few things in the hope that that invalidates more pointers.


For me, this is what my list looks like after the first scan already. Number of pointers I could use is pretty low there already so there was no rescan needed.
![image](https://user-images.githubusercontent.com/23149710/108101697-e0d6c700-7087-11eb-858b-655566a2ad6c.png)

**Comment by MrSlimbrowser** [comment]
I would also recommend to add the pointers you found to a cheattable and save it somewhere (aka double click each of them so they show up in the list on the left side, close the pointer scan window and hit File->"Save as" in Cheat Engine. Sometimes you may be unlucky and the pointer you used stops working after a while (sometimes even weeks), then you can just open up the cheattable, attach to iCUE.exe and look for another pointer that still works without the need to rescan.

**Comment by Mouse703** [comment]
Ok, after some setbacks I got it working, thank you for you great clarification of the pointers. It seems to work right now.
